name: cisco-configuration-downloader
summary: Cisco configuration downloader
description: >
  Cisco configuration downloader
version: '1.0'

grade: stable
base: core18
confinement: strict

apps:
  cisco-configuration-downloader:
    command: bin/ccd.sh
    plugs:
      - home

parts:
  cisco-configuration-downloader:
    source: .
    plugin: dump
    organize:
      ccd.sh: bin/