name: cisco-configuration-downloader
version: 1.0
summary: A program for downloading configuration from Cisco devices.
description: |
  Thanks to the program, you can easily download the current configuration from a Cisco device.
  The program automatically assigns a unique file name and copies the file to the appropriate folder.

grade: stable
confinement: strict

apps:
  nazwa-mojej-aplikacji:
    command: usr/bin/bash $SNAP/bin/ccd
    plugs: [home, network]

parts:
  moj-skrypt:
    plugin: nil
    source: .
    build-packages: [bash]
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp src/ccd $SNAPCRAFT_PART_INSTALL/bin/