name: cisco-configuration-downloader
version: 1.0
summary: A program for downloading configuration from Cisco devices.
description: |
  Thanks to the program, you can easily download the current configuration from a Cisco device.
  The program automatically assigns a unique file name and copies the file to the appropriate folder.

grade: stable
confinement: strict

apps:
  ccd:
    command: bin/ccd.sh

parts:
  skrypt-bash:
    plugin: nil
    stage-packages:
      - bash
    source: .
    organize:
      'ccd.sh': bin/ccd.sh